### ISSUE TITLE
Source Request

### ISSUE THREAD

**Issue by huxxyfromjupiter** [IReaderorg/IReader-extensions#10]
<s>[https://www.novelupdates.com/](url)</s>
<s>[https://1stkissnovel.love/home-novel/](url)</s>
<s>[https://daonovel.com/](url)</s>
<s>[https://allnovelfull.com/](url)</s>
[https://www.novelupdates.cc/](url)
[https://www.wuxia.blog/](url)
[https://www.dongliuxiaoshuo.com/](url)
<s>[https://www.lightnovelpub.com/app](url)</s>
<s>[https://lightnovelreader.org/](url)</s>
<s>[https://skynovel.org/](url)</s>
[https://vipnovel.com/](url)
<s>[https://www.novelpub.com/get](url)</s>
<s>[https://novelfull.com/](url)</s>
<s>[https://www.readwn.com/search.html](url)</s>
<s>[https://www.scribblehub.com/](url)</s>
<s>[https://mostnovel.com/](url)</s>
[https://webnovelonline.com/](url)
[https://www.sonicmtl.com/](url)
[https://clicknovel.net/](url)
[https://freenovel.me/](url)
[https://www.feiszw.com/](url)
<s>[https://m.wuxiaworld.co/](url)</s>
[https://www.wuxiaworld.eu/](url)
[https://www.bxwx.la/](url)

Please add auto translate option in Multilingual sources just like you did in mtlnation ( i think )

**Comment by kazemcodes** [comment]
skynovel source was created

**Comment by kazemcodes** [comment]
dao novel was created.
please open sperate source request for rach one you mentioned
