### ISSUE TITLE
 Multiple Arabic sources add

### ISSUE THREAD

**Issue by yemenihandsome** [IReaderorg/IReader-extensions#20]
<s>https://teamxnovel.com/</s>
https://sunovels.com/
<s>https://ar-mtl.club/<s>
<s>https://novel4up.com/</s>
https://rewayat.club/
https://arnovel.me/
<s>https://novelparadise.net/<s>
<s>https://kolnovel.com/</s>
https://hizomanga.com

**Comment by yemenihandsome** [comment]
@kazemcodes Thank you for not adding the wonderful Arabic sources. I have left these sources not added:

https://sunovels.com/
https://rewayat.club/
https://hizomanga.com/
https://arnovel.me/

**Comment by kazemcodes** [comment]
> @kazemcodes Thank you for adding the wonderful Arabic sources. I have left these sources not added:
> 
> https://sunovels.com/ https://rewayat.club/ https://hizomanga.com/ https://arnovel.me/ https://novelparadise.website/

Please open separate issue for each source
