### ISSUE TITLE
[Source Request] NeoSekai Translation

### ISSUE THREAD

**Issue by mystic-man-rhino** [IReaderorg/IReader-extensions#26]
**Name**:        NeoSekai Translation
**Language**:  EN
**URL**:           https://www.neosekaitranslations.com/

Using wordpress madara theme

**Comment by kazemcodes** [comment]
this extension is not completely working as I tried to use Madara multisrc to make it and probably there are some problem in there, you can use the fetch function in webview to fetch books and chapters, and app can only fetch chapter using the site api
