### ISSUE TITLE
adding repository

### ISSUE THREAD

**Issue by yuval989** [IReaderorg/IReader-extensions#42]
hey how are i am trying to add an url throught the app but every time it show a message that says "invalid url" althougg i also tried to type url from this url extensions. i will be more than happy if you can guide me throught the app and how to add a new url

**Comment by yuval989** [comment]
can i add books from my archive or my computer storage ? without using a website just openning and viewing a pdf

**Comment by kazemcodes** [comment]
> hey how are i am trying to add an url throught the app but every time it show a message that says "invalid url" althougg i also tried to type url from this url extensions. i will be more than happy if you can guide me throught the app and how to add a new url

A valid repo URL is like this
https://raw.githubusercontent.com/kazemcodes/source-test/main/index.min.json#name=IReader-Preview#owner=kazemcodes#source=github##

**Comment by kazemcodes** [comment]
> can i add books from my archive or my computer storage ? without using a website just openning and viewing a pdf

Right now, the app doesn't support pdfs, it can open epubs and export books as epubs

**Comment by kazemcodes** [comment]
> > can i add books from my archive or my computer storage ? without using a website just openning and viewing a pdf
> 
> Right now, the app doesn't support pdfs, it can open epubs and export books as epubs

But supporting pdf is not really hard. At least it's easier than epub

**Comment by kazemcodes** [comment]
> > hey how are i am trying to add an url throught the app but every time it show a message that says "invalid url" althougg i also tried to type url from this url extensions. i will be more than happy if you can guide me throught the app and how to add a new url
> 
> A valid repo URL is like this https://raw.githubusercontent.com/kazemcodes/source-test/main/index.min.json#name=IReader-Preview#owner=kazemcodes#source=github##

I created one before
https://github.com/kazemcodes/source-test

**Comment by kazemcodes** [comment]
> can you send me your e-mail for a business

kazem.codes@gmail.com
