### ISSUE TITLE
KolNovel :  It causes the program to crash

### ISSUE THREAD

**Issue by yemenihandsome** [IReaderorg/IReader-extensions#56]
When entering this source, the program automatically collapses and stops for me

**Comment by kazemcodes** [comment]
Remove the extension then install it again, it will be fixed

**Comment by kazemcodes** [comment]
Also check if you are using latest version or not

**Comment by kazemcodes** [comment]
Also check if you are using latest version or not

**Comment by yemenihandsome** [comment]
@kazemcodes I am using the latest version, but the source is causing the crash
